@startuml
actor Cliente
participant "Cajero automático" as Cajero
participant "Sistema bancario" as Sistema

Cliente -> Cajero : Insertar tarjeta y autenticar
Cajero -> Sistema : Verificar usuario y contraseña
Sistema -> Cajero : Confirmar autenticación exitosa
Cliente -> Cajero : Solicitar retiro y monto
Cajero -> Sistema : Verificar saldo y validar retiro
Sistema -> Cajero : Confirmar disponibilidad de fondos
Cajero -> Cliente : Realizar retiro
@enduml

@startuml
actor Cliente
participant "Cajero automático" as Cajero
participant "Sistema bancario" as Sistema

Cliente -> Cajero : Insertar tarjeta y autenticar
Cajero -> Sistema : Verificar usuario y contraseña
Sistema -> Cajero : Confirmar autenticación exitosa
Cliente -> Cajero : Solicitar consulta de movimientos
Cajero -> Sistema : Solicitar historial de movimientos
Sistema -> Cajero : Enviar movimientos recientes
Cajero -> Cliente : Mostrar movimientos
@enduml


@startuml
actor Cliente
participant "Cajero automático" as Cajero
participant "Sistema bancario" as Sistema

Cliente -> Cajero : Insertar tarjeta y autenticar
Cajero -> Sistema : Verificar usuario y contraseña
Sistema -> Cajero : Confirmar autenticación exitosa
Cliente -> Cajero : Solicitar transferencia
Cliente -> Cajero : Ingresar cuenta destino y monto
Cajero -> Sistema : Validar cuenta destino y saldo
Sistema -> Cajero : Confirmar validación exitosa
Cajero -> Cliente : Solicitar confirmación de transferencia
Cliente -> Cajero : Confirmar transferencia
Cajero -> Sistema : Procesar transferencia
Sistema -> Cajero : Confirmar transacción exitosa
Cajero -> Cliente : Imprimir recibo de transferencia
@enduml



